Add support for entering tax as a percentage of Total
relistan/billmonger pull request #4
Opened 2019-12-05 10:52 UTC by arimbun

Simple support to configure tax as a percentage of Total in the `billing.yaml` file.

2019-12-29 22:41 UTC, relistan commented
Sorry I missed this when you opened it! Will review tomorrow. Thanks for the contribution @arimbun

2020-01-11 06:56 UTC, arimbun commented
@relistan No problem, did you have a chance to review it?

2020-02-29 17:46 UTC, relistan commented on billing.example.yaml
> +  percentage: 0.1
We really need to support a default tax and an overridable tax rate per item. Some items may be taxable at different rates.

2020-02-29 17:46 UTC, relistan commented on billing.example.yaml
> +tax:
```suggestion
default_tax:
```

2020-02-29 17:47 UTC, relistan commented on invoice/config.go
> +type TaxDetails struct {
We should call this something like `DefaultTax` instead.

2020-02-29 17:48 UTC, relistan commented on invoice/bill.go
> +	b.textFormat(widths[len(widths)-2], 4, "GST", "1", 0, "R", true, 0, "")
```suggestion
	b.textFormat(widths[len(widths)-2], 4, "Tax", "1", 0, "R", true, 0, "")
```

GST is a region-specific tax for certain countries. Let's stay with generic "Tax"

2020-02-29 17:50 UTC, relistan requested changes
@arimbun MANY apologies for taking so darn long to get to this. It's a side project and finding time can be a challenge. This looks pretty good. I would like to eventually allow item-specific tax calculation, so I've pointed out where I'd like to change what you've got here. Otherwise, good to go. Thank you for the contribution! Again, sorry about how long it took to get to it. @rolandtritsch 's PR was waiting on me for quite awhile as well.

2020-02-29 17:51 UTC, relistan commented on billing.example.yaml
> +tax:
You'll need to make various adjustments elsewhere in the code to make this work also. Didn't try to find them all.

2020-02-29 17:52 UTC, relistan commented on invoice/bill.go
> +	b.textFormat(widths[len(widths)-2], 4, "GST", "1", 0, "R", true, 0, "")
Alternatively, make this configurable in the `default_tax` block in the config.

2020-03-01 13:38 UTC, relistan commented
Hey @arimbun I've got a little time to deal with this today so I'm going to merge it as-is and do a little work on it now. Thanks again for the contribution!

2020-03-01 13:38 UTC, merged

2020-03-02 05:40 UTC, rolandtritsch commented
@relistan @arimbun Nice!!!